### ISSUE TITLE
Problem with read names that end in /1 & /2

### ISSUE THREAD

**Issue by mbyott** [ChrisHIV/shiver#13]
My original read names look like:
`@M03972:191:000000000-CJT9T:1:1101:12698:6609 1:N:0:CTCTCTAC+GCGTAAGA`

I have amended them to look like:
`@M03972:191:000000000-CJT9T:1:1101:12698:6609/1:N:0:CTCTCTAC+GCGTAAGA`

I have also removed the information after the /1 /2 that was introduced in Casava 1.8, giving me:
`@M03972:191:000000000-CJT9T:1:1101:12698:6609/1`

But I still get the `Problem with read names. Quitting.` error.  Do you have any advice?

**Comment by ChrisHIV** [comment]
Hi there. The output immediately before `Problem with read names. Quitting.` should say what the problem is. Lines 288-289 of `shiver_map_reads.sh` are
```
(CheckReadNames "$reads1" 1 && CheckReadNames "$reads2" 2 || \
{ echo 'Problem with read names. Quitting.' >&2 ; exit 1 ; })
```
and the `CheckReadNames` function defined at line 170 of `shiver_funcs.sh` reports one of three reasons for failing: reads do not end in /1 or /2, or read names are not unique, or read names contain a tab character (which would interfere with subsequent processing of the read names).

**Comment by ChrisHIV** [comment]
If it's still not clear after this, perhaps you can provide a dummy pair of fastq files with just one pair of reads named like this (removing any sensitive sequence data) that reproduces the error?

**Comment by mbyott** [comment]
[test.reads_2.fastq.gz](https://github.com/ChrisHIV/shiver/files/9625619/test.reads_2.fastq.gz)
[test.reads_1.fastq.gz](https://github.com/ChrisHIV/shiver/files/9625620/test.reads_1.fastq.gz)


Thanks @ChrisHIV , I've checked for tabs and identical read names and still get that error. I've attached a single read pair. My command is:

`shiver_map_reads.sh shiver.initDir config.sh sample.contigs.fasta sampleID sampleID.blast sampleID_cut_wRefs.fasta test.reads_1.fastq test.reads_2.fastq`

**Comment by ChrisHIV** [comment]
Sorry for the delay. I get the error with those files too, and I think it's caused by the linebreaks being encoded by something other than "\n". I can't see what the encoding is; perhaps these files were generated on Windows, which encodes with "\r\n"? Whatever the encoding is, awk handles it incorrectly. I'm able to fix the problem by running 
```
python2 ~/shiver/tools/RemoveTrailingWhitespace.py my_old_reads_file > my_new_reads_file
```
which simply replaces linebreak encoding with "\n". (The reads file needs to be unzipped before processing it this way)

**Comment by mbyott** [comment]
Thanks, this solved the problem.
