### ISSUE TITLE
Issue with shiver_map_reads.sh - temp_ContaminantReads_1.txt contains reads but 0 in temp_reads1trim2.fastq

### ISSUE THREAD

**Issue by stephaniemel** [ChrisHIV/shiver#14]
Hi Chris,

I'm encountering issues running the "shiver_map_reads.sh" using my own dataset of HIV sequences. After successfully running "shiver_align_contigs.sh", the "shiver_map_reads.sh" function has always quit on my own dataset (it has worked when I use files from the ExampleInput folder). 

Before quitting it returns "temp_ContaminantReads_1.txt contains (e.g. 275913) reads but we only found 0 in temp_reads1trim2.fastq."
The last file created in the output directory is always the 'T1076_PreMapping_1.fastq' file. Typically, it runs for quite a while i.e. several hours before I come across this issue. Below I have pasted my input command and the verbose.

I am unsure what the issue and next steps to take. I'd greatly appreciate any help or advice you may have!

Thanks,
Stephanie

Info: shiver_map_reads.sh was called thus:
/mnt/c/Users/smelnych/Desktop/shiver/shiver_map_reads.sh /mnt/c/Users/smelnych/Desktop/shiver/MyInitDir_hiv /mnt/c/Users/smelnych/Desktop/shiver/config_original.sh T1076prrt_contigs.fasta T1076 T1076.blast T1076_cut_wRefs.fasta T1076-PRRT_R_1_renamed.fastq T1076-PRRT_R_2_renamed.fastq
With these config file parameter values:
MaxContigGappiness=0.05
MinContigHitFrac=0.9
python2='python2'
BlastDBcommand='makeblastdb'
BlastNcommand='blastn'
smalt='smalt'
bwa='bwa'
bowtie2='bowtie2'
bowtie2_build='bowtie2-build'
samtools='samtools'
mafft='mafft'
fastaq='fastaq'
trimmomatic="trimmomatic"
MafftArgsForPairwise='--maxiterate 1000 --localpair'
MinContigLength=300
MinGapSizeToSplitGontig=160
MinContigFragmentLength=80
TrimToKnownGenome=true
BlastTasks='megablast'
ContigBlastArgs="-max_target_seqs 1 -word_size 17"
ContigMinBlastOverlapToMerge='2'
MafftTestingStrategy="MinAlnLength"
TrimReadsForAdaptersAndQual=true
IlluminaClipParams='2:10:7:1:true'
BaseQualityParams='MINLEN:50 LEADING:20 TRAILING:20 SLIDINGWINDOW:4:20'
NumThreadsTrimmomatic=1
TrimReadsForPrimers=true
TrimPrimerWithOneSNP=false
CleanReads=true
mapper="smalt"
smaltIndexOptions="-k 15 -s 3"
smaltMapOptions="-x -y 0.7 -j 0 -i 2000"
bowtieOptions="--local --maxins 2000 --no-discordant --no-unal --quiet"
bwaOptions='-v 2'
samtoolsReadFlags='-f 3 -F 4'
mpileupOptions='--no-BAQ --min-BQ 5 --max-depth 1000000'
MinCov1=15
MinCov2=30
MinBaseFrac=-1
deduplicate=false
DeduplicationCommand="picard MarkDuplicates"
remap=true
MapContaminantReads=false
GiveHXB2coords=true
AlignContigsToConsensus=false
KeepPreMappingReads=false
###############################################

Info: using CON_B(1295)_Pol (elongated with other longer references if needed) to provide 1722 bases to fill in gaps before/between/after contigs. This reference was the best match for the contigs: 94.1466854725% of positions in agreement.
Now trimming reads - typically a slow step.
Skipping duplicate Clipping Sequence: 'GACGCTGCCGACGATCTTACGCGTGTAGATCTCGGTGGTCGCCGTATCATT'
Skipping duplicate Clipping Sequence: 'CCGAGCCCACGAGACCGTACTAGATCTCGTATGCCGTCTTCTGCTTG'
Skipping duplicate Clipping Sequence: 'CCGAGCCCACGAGACTAAGGCGAATCTCGTATGCCGTCTTCTGCTTG'
Skipping duplicate Clipping Sequence: 'CCGAGCCCACGAGACTCCTGAGCATCTCGTATGCCGTCTTCTGCTTG'
Skipping duplicate Clipping Sequence: 'CCGAGCCCACGAGACAGGCAGAAATCTCGTATGCCGTCTTCTGCTTG'
Skipping duplicate Clipping Sequence: 'CCGAGCCCACGAGACTAGGCATGATCTCGTATGCCGTCTTCTGCTTG'
Skipping duplicate Clipping Sequence: 'CCGAGCCCACGAGACGGACTCCTATCTCGTATGCCGTCTTCTGCTTG'
Skipping duplicate Clipping Sequence: 'CCGAGCCCACGAGACCTCTCTACATCTCGTATGCCGTCTTCTGCTTG'
Skipping duplicate Clipping Sequence: 'CCGAGCCCACGAGACGTAGAGGAATCTCGTATGCCGTCTTCTGCTTG'
Skipping duplicate Clipping Sequence: 'CCGAGCCCACGAGACAAGAGGCAATCTCGTATGCCGTCTTCTGCTTG'
Skipping duplicate Clipping Sequence: 'CCGAGCCCACGAGACCGAGGCTGATCTCGTATGCCGTCTTCTGCTTG'
Skipping duplicate Clipping Sequence: 'GACGCTGCCGACGATACTCCTTGTGTAGATCTCGGTGGTCGCCGTATCATT'
Skipping duplicate Clipping Sequence: 'GACGCTGCCGACGAAGGCTTAGGTGTAGATCTCGGTGGTCGCCGTATCATT'
Skipping duplicate Clipping Sequence: 'GACGCTGCCGACGACTCCTTACGTGTAGATCTCGGTGGTCGCCGTATCATT'
Skipping duplicate Clipping Sequence: 'GACGCTGCCGACGATATGCAGTGTGTAGATCTCGGTGGTCGCCGTATCATT'
Skipping duplicate Clipping Sequence: 'GACGCTGCCGACGAAGAGGATAGTGTAGATCTCGGTGGTCGCCGTATCATT'
Skipping duplicate Clipping Sequence: 'GACGCTGCCGACGAATAGAGAGGTGTAGATCTCGGTGGTCGCCGTATCATT'
fastaq completed successfully.

Building a new DB, current time: 01/18/2023 13:46:57
New DB name:   /mnt/c/Users/smelnych/Desktop/shiver/hiv/fastq/T1076/temp_BlastDB
New DB title:  temp_RefAndContaminantContigs.fasta
Sequence type: Nucleotide
Keep MBits: T
Maximum file size: 3000000000B
Adding sequences from FASTA; added 45 sequences in 0.093262 seconds.

Now blasting the reads - typically a slow step.
Warning: [blastn] Examining 5 or more matches is recommended
Warning: [blastn] Examining 5 or more matches is recommended
Error: temp_ContaminantReads_1.txt contains 275913 reads but we only found 0 in temp_reads1trim2.fastq.
Problem extracting the non-contaminant reads using /mnt/c/Users/smelnych/Desktop/shiver/tools/FindNamedReadsInSortedFastq.py. Quitting.

**Comment by ChrisHIV** [comment]
Hi Stephanie,
I've not seen this problem before, strange. `temp_reads1trim2.fastq` should contain the forward (1) reads at an intermediate stage of processing through the pipeline. `temp_ContaminantReads_1.txt` should contain a plain-text new-line-separated list of reads from `temp_reads1trim2.fastq` for which the best blast match is one of the contigs that was previously identified as being a contaminant contig. The shiver tool `FindNamedReadsInSortedFastq.py` is finding many suspect reads named in the plain-text list but none of those reads were found in the reads file. Can you check whether `temp_reads1trim2.fastq` is empty? If it's not, can you pick one of the suspicious read names in `temp_ContaminantReads_1.txt` and try manually searching for it in `temp_reads1trim2.fastq` e.g. opening that fastq file with a plain-text editor and searching? If you do find it, what happens if you make a new test contaminant read list called e.g. `test.txt` that contains only the name of that read, and a new read file called e.g. `test.fastq`, and then you run `python2 /mnt/c/Users/smelnych/Desktop/shiver/tools/FindNamedReadsInSortedFastq.py -v -s test.fastq test.txt`, replacing `python2` by whatever python2 command is appropriate in your case (the same thing you choose for `python2` in the config file)? Would you be able to share
1. an example file of reads (e.g. the full `temp_reads1trim2.fastq` file that's causing the problem, or some subset of reads from it), and
2. an example plain-text new-line-separated file listing the names of some reads from that file (e.g. the full `temp_ContaminantReads_1.txt` file that's causing the problem, or some subset of the names in it corresponding to whatever subset you took in step 1, i.e. this list should not contain the names of any reads that are missing from the associated read file) 

?
Alternatively if `temp_reads1trim2.fastq` was empty, or genuinely was missing the reads that are named in `temp_ContaminantReads_1.txt`, then something has gone wrong in generating that reads file as opposed to just a problem with `FindNamedReadsInSortedFastq.py` finding the reads. If that's the case I might need the full set of input files to the `shiver_map_reads.sh` command to be able to figure out what's going on, or some reduction of that data (e.g. manually extracting some of the input reads) that still allows reproduction of the problem.
I'll only be able to resume debugging this on Monday, apologies

**Comment by stephaniemel** [comment]
Hi Chris,
Really appreciate the prompt response. A few answers to your suggestions:

`temp_reads1trim2.fastq` is not empty, and I was able to find specific read names in this file named in the `temp_ContaminantReads_1.txt` through manually searching in a plain-text editor.
I made a new test contaminant read list and new read file to run `python2 /mnt/c/Users/smelnych/Desktop/shiver/tools/FindNamedReadsInSortedFastq.py -v -s test.fastq test.txt` The output was as follows:
Error: test.txt contains 1 reads but we only found 0 in test.fastq.

Any ideas what could be going on here?
I'll have to get back to you in regard to sharing some providing some files next week as well. Thanks again for your quick assistance!

**Comment by ChrisHIV** [comment]
Hi Stephanie, sorry I forgot this on Monday. It looks like something unexpected is going wrong in the `FindNamedReadsInSortedFastq.py` code. Are you able to share that read file containing only one read, and the associated contaminant list file naming that read, to see if I can reproduce the error?
